apiVersion: v1
kind: Pod
metadata:
  name: yellow
  namespace: dev
  labels:
    name: yellow
    app: yellow
spec:
  containers:
    - name: lemon
      image: busybox
    - name: gold
      image: redis
