apiVersion: v1
kind: Service
metadata:
  name: mysql-customer-db-service
  labels:
    name: customer-db-service
    app: customer-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
     name: mysql-customer-db-pod
     app: customer-app


