apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs-customer-app
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Mi