apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-logs
  namespace: dev
spec:
  #storageClassName: base
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /zivasera/apps/logs
