apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: dev
spec:
  #storageClassName: base
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /zivasera/mysql-data
