apiVersion: v1
kind: Service
metadata:
  name: catalog-app-sevice
  labels:
    name: catalog-app-service
    app: catalog-app
spec:
    type: NodePort
    ports:
      - port: 12090
        targetPort: 8080
        nodePort: 30090
    selector:
      name: catalog-app-pod
      app: catalog-app


