apiVersion: v1
kind: Pod
metadata:
  name: catalog-app-pod
  labels:
    name: catalog-app-pod
    app: catalog-app
spec:
  containers:
    - name: catalog-app
      image: cpsarathe/demo-ecom-repo:catalog
      ports:
        - containerPort: 8080
      env:
        - name: MYSQL_HOST
          value: mysql-catalog-db-service
        - name : MYSQL_SCHEMA
          value : catalog-db
