apiVersion: v1
kind: Service
metadata:
  name: customer-app-sevice
  labels:
    name: customer-app-service
    app: customer-app
spec:
    type: NodePort
    ports:
      - port: 9080
        targetPort: 9080
        nodePort: 30080
    selector:
      name: customer-app-pod
      app: customer-app


